language: python
sudo: true

before_install:
  - sudo wget ftp.wayne.edu/gnu/gsl/gsl-2.6.tar.gz
  - tar -xzvf gsl-2.6.tar.gz
  - cd gsl-2.6
  - ./configure
  - make
  - make install

install:
    - pip install tox

script:
    - tox -r

matrix:
    include:
        - python: 3.8
          env: TOXENV=testenv
          dist: xenial

        - python: 3.8
          env: TOXENV=style
          dist: xenial

        - python: 3.8
          env: TOXENV=coverage
          dist: xenial

        - python: 3.8
          env: TOXENV=docstyle
          dist: xenial

        - python: 3.8
          env: TOXENV=docs
          dist: xenial
