language: python
sudo: true

before_install:
    - sudo apt-get install libgsl-dev

install:
    - pip install tox

script:
    - tox -r

matrix:
    include:
        - python: 3.8
          env: TOXENV=py38
          dist: xenial

        - python: 3.8
          env: TOXENV=style
          dist: xenial

        - python: 3.8
          env: TOXENV=coverage
          dist: xenial

        - python: 3.8
          env: TOXENV=docstyle
          dist: xenial

        - python: 3.8
          env: TOXENV=docs
          dist: xenial
