language: python
sudo: False

install:
    - pip install tox

script:
    - tox -r

matrix:
    include:
        - python: 3.8
          env: TOXENV=style
          dist: xenial

        - python: 3.8
          env: TOXENV=coverage
          dist: xenial

        - python: 3.8
          env: TOXENV=docstyle
          dist: xenial

